apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 80           # Porta do serviço
      targetPort: 5000   # Porta do container
  type: NodePort
