services:
  test_app:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: test_app
    ports:
      - ${PORT:-4000}:4000 
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-2020}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-resume_submission_test}
    networks:
      - app-network
    depends_on:
      - db
    
    # entrypoint em desenvolvimento e ou teste
    entrypoint: [
      "sh", "-c", "
      npx prisma generate && 
      npx prisma migrate dev && 
      npx prisma db seed && 
      npm run build && 
      npm start"
    ]

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5433}:5432 #5433 é a porta do container e o 5432 é a porta do hosts
    volumes:
      - postgres_data:/var/lib/postgresql/data  #postgres_data é o nome do volume
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-2020}
      POSTGRES_DB: ${POSTGRES_DB:-resume_submission_test}
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge