services:
  test_app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: test_app
    ports:
      - ${PORT:-4000}:4000
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_URL: 'postgres://postgres:2020@db:5432/resume_submission_test'
    networks:
      - app-network
    depends_on:
      - db
    entrypoint: [
      "sh", "-c", "
      npx prisma generate && 
      npx prisma migrate dev && 
      npx prisma db seed && 
      npm run build && 
      npm start"
    ]
 
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    tty: true
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # POSTGRES_PORT: ${POSTGRES_PORT} 
      # DATABASE_URL: 'postgres://postgres:2020@db:5432/resume_submission_test'
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge