version: '6.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.yml  
    container_name: resume_project
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_PASSWORD: '2020'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'resume_submission_test'
      POSTGRES_PORT: '5433'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - app-network
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && npx prisma migrate dev --preview-feature && npx prisma db seed && npm start"]

  db:
    image: postgres
    container_name: postgres
    restart: always
    tty: true
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: '2020'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'resume_submission_test'
      POSTGRES_PORT: '5432' 
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
